// login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const FB_LOGIN_REQUEST = "FB_LOGIN_REQUEST";
export const FB_LOGIN_RESPONSE = "FB_LOGIN_RESPONSE";
export const GMAIL_LOGIN_REQUEST = "GMAIL_LOGIN_REQUEST";
export const GMAIL_LOGIN_RESPONSE = "GMAIL_LOGIN_RESPONSE";
//forgotPassword
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_RESPONSE = "FORGOT_PASSWORD_RESPONSE";

export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";

//logout
export const LOGOUT = "LOG_OUT";

//register
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_RESPONSE = "REGISTER_RESPONSE";
//loaders
export const LOADING_ENABLE_LOADER = "LOADING_ENABLE_LOADER";
export const LOADING_DISABLE_LOADER = "LOADING_DISABLE_LOADER";
//TOAST
export const ENABLE_SNACKBAR = "ENABLE_SNACKBAR";
export const DISABLE_SNACKBAR = "DISABLE_SNACKBAR";
//get donation types
export const GET_DONATION_TYPE_REQUEST = "GET_DONATION_TYPE_REQUEST";
export const GET_DONATION_TYPE_RESPONSE = "GET_DONATION_TYPE_RESPONSE";
//Top Contributes
export const GET_TOP_CHARITIES_REQUEST = "GET_TOP_CHARITIES_REQUEST";
export const GET_TOP_CHARITIES_RESPONSE = "GET_TOP_CHARITIES_RESPONSE";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CLEAR_SELECTED_PRODUCTS = "CLEAR_SELECTED_PRODUCTS";

//Countries
export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST";
export const GET_COUNTRIES_RESPONSE = "GET_COUNTRIES_RESPONSE";
//State
export const GET_STATE_REQUEST = "GET_STATE_REQUEST";
export const GET_STATE_RESPONSE = "GET_STATE_RESPONSE";
//Cities
export const GET_CITIES_REQUEST = "GET_CITIES_REQUEST";
export const GET_CITIES_RESPONSE = "GET_CITIES_RESPONSE";
//Order
export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_RESPONSE = "ORDER_RESPONSE";
//

//User Profile Image
export const PROFILE_IMAGE_REQUEST = "PROFILE_IMAGE_REQUEST";
export const PROFILE_IMAGE_RESPONSE = "PROFILE_IMAGE_RESPONSE";
//favourite
// Get Donation
export const GET_DONATION_REQUEST = "GET_DONATION_REQUEST";
export const GET_DONATION_RESPONSE = "GET_DONATION_RESPONSE";
//Update Profile
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_RESPONSE = "UPDATE_PROFILE_RESPONSE";
//About
export const GET_ABOUT_DATA_REQUEST = "GET_ABOUT_DATA_REQUEST";
export const GET_ABOUT_DATA_RESPONSE = "GET_ABOUT_DATA_RESPONSE";
//contact
export const GET_CONTACT_DATA_REQUEST = "GET_CONTACT_DATA_REQUEST";
export const GET_CONTACT_DATA_RESPONSE = "GET_CONTACT_DATA_RESPONSE";
//contact us
export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_RESPONSE = "CONTACT_US_RESPONSE";
//
export const SAVE_SELECTED_CATEGORY = "SAVE_SELECTED_CATEGORY";
//terms policy data
export const TERMS_POLICY_DATA_REQUEST = "TERMS_DATA_REQUEST";
export const TERMS_POLICY_DATA_RESPONSE = "TERMS_DATA_RESPONSE";
//privacy data
export const PRIVACY_DATA_REQUEST = "PRIVACY_DATA_REQUEST";
export const PRIVACY_DATA_RESPONSE = "PRIVACY_DATA_RESPONSE";
//sliderVisible
export const SLIDER_VISIBLE = "SLIDER_VISIBLE";
//save history
export const UPDATE_SEARCH_HISTORY = "UPDATE_SEARCH_HISTORY";
export const CLEAR_SEARCH_HISTORY = "CLEAR_SEARCH_HISTORY";
// save current Location
export const SAVE_CURRENT_LOCATION = "SAVE_CURRENT_LOCATION";
//get least food
export const GET_LATEST_FOOD_TRENDS_REQUEST = "GET_LATEST_FOOD_TRENDS_REQUEST";
export const GET_LATEST_FOOD_TRENDS_RESPONSE =
   "GET_LATEST_FOOD_TRENDS_RESPONSE";
// around you vendor
export const GET_VENDORS_AROUND_YOU_REQUEST = "GET_VENDORS_AROUND_YOU_REQUEST";
export const GET_VENDORS_AROUND_YOU_RESPONSE =
   "GET_VENDORS_AROUND_YOU_RESPONSE";
// around you charity
export const GET_CHARITY_AROUND_YOU_REQUEST = "GET_CHARITY_AROUND_YOU_REQUEST";
export const GET_CHARITY_AROUND_YOU_RESPONSE =
   "GET_CHARITY_AROUND_YOU_RESPONSE";
// cancel order
export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
//around me
export const GET_AROUND_ME_REQUEST = "GET_AROUND_ME_REQUEST";
export const GET_AROUND_ME_RESPONSE = "GET_AROUND_ME_RESPONSE";
// around you
export const GET_REWARDS_DATA_REQUEST = "GET_REWARDS_DATA_REQUEST";
export const GET_REWARDS_DATA_RESPONSE = "GET_REWARDS_DATA_RESPONSE";
